src/objects/Async_Task__c.object
<CustomObject>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Async Task</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Async Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SOListAsync.cls
public class SOListAsync {
	List<Async_Task__c> operations;
    List<sObject> lst;
    
    public SOListAsync(List<sObject> objects) {
        this(objects, new List<Async_Task__c>());
    }
    
    public SOListAsync(List<sObject> objects, List<Async_Task__c> operations) {
        this.lst = objects;
        this.operations = operations;
    }
    
    public SOListAsync mapper(String fn) {
        this.operations.add(new Async_Task__c(Type__c = 'mapper', Function__c=fn));
        return new SOListAsync(this.lst, this.operations);
    }
}